version: '2'

services:

  mauticdb:
    image: percona/percona-server:5.7
    container_name: mauticdb
    volumes:
      - mysql_data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    networks:
      - mautic-net

  mautic:
    image: mautic/mautic:v4
    container_name: mautic
    links:
      - mauticdb:mysql
    depends_on:
      - mauticdb
    ports:
      - 80:80
    volumes:
      - mautic_data:/var/www/html
    env_file: .env
    environment:
      MAUTIC_DB_HOST: ${MAUTIC_DB_HOST}
      MYSQL_PORT_3306_TCP: ${MYSQL_PORT_3306_TCP}
      MAUTIC_DB_USER: ${MAUTIC_DB_USER}
      MAUTIC_DB_PASSWORD: ${MAUTIC_DB_PASSWORD}
      MAUTIC_DB_NAME: ${MAUTIC_DB_NAME}
      MAUTIC_RUN_CRON_JOBS: ${MAUTIC_RUN_CRON_JOBS}
    networks:
      - mautic-net

volumes:
  mysql_data:
    driver: local
  mautic_data:
    driver: local
networks:
  mautic-net:
    driver: bridge